### ISSUE TITLE
elevio.logout() throws an error if Elevio is disabled

### ISSUE THREAD

**Issue by ForSpareParts** [seawatts/ember-elevio#65]
Because the `elevio` service's `logout()` method does not check whether Elevio is actually enabled, calling `logout()` while elevio is disabled causes an error (because the `logoutUser()` method does not exist on an empty hash). To solve this, `logout()` needs to check whether we really have an Elevio instance, or the Elevio stub needs to provide a no-op `logoutUser()`.

**Comment by seawatts** [comment]
Thanks for the feedback. I'm about to start working on this again and I'll see what I can to do get this closed.

**Comment by seawatts** [comment]
This should be fixed in https://github.com/seawatts/ember-elevio/releases/tag/v0.2.0
